package com.vehicle.immatriculation.vin.model

data class Detail(
    val erreur: String? = null,
    val immat: String?,
    val co2: String?,
    val energie: String?,
    val energieNGC: String?,
    val genreVCG: Long?,
    val genreVCGNGC: String?,
    val puisFisc: String?,
    val carrosserieCG: String?,
    val marque: String?,
    val modele: String?,
    val date1erCirUs: String?,
    val date1erCirFr: String?,
    val collection: String?,
    val date30: String?,
    val vin: String?,
    val boiteVitesse: String?,
    val puisFiscReel: String?,
    val nrPassagers: String?,
    val nbPortes: String?,
    val typeMine: String?,
    val couleur: String?,
    val poids: String?,
    val cylindres: String?,
    val sraId: String?,
    val sraGroup: String?,
    val sraCommercial: String?,
    val logoMarque: String?,
    val codeMoteur: String?,
    val kType: String?,
)
