package com.vehicle.immatriculation.vin.model

data class Detail(
    val erreur: String? = null,
    val immat: String? = null,
    val co2: String? = null,
    val energie: String? = null,
    val energieNGC: String? = null,
    val genreVCG: Long? = null,
    val genreVCGNGC: String? = null,
    val puisFisc: String? = null,
    val carrosserieCG: String? = null,
    val marque: String? = null,
    val modele: String? = null,
    val date1erCirUs: String? = null,
    val date1erCirFr: String? = null,
    val collection: String? = null,
    val date30: String? = null,
    val vin: String? = null,
    val boiteVitesse: String? = null,
    val puisFiscReel: String? = null,
    val nrPassagers: String? = null,
    val nbPortes: String? = null,
    val typeMine: String? = null,
    val couleur: String? = null,
    val poids: String? = null,
    val cylindres: String? = null,
    val sraId: String? = null,
    val sraGroup: String? = null,
    val sraCommercial: String? = null,
    val logoMarque: String? = null,
    val codeMoteur: String? = null,
    val kType: String? = null,
)
