name: Android Build

on:
  push:
    branches: [ master ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      # Run Tests Build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create-secrets-properties
        run: echo rapidApiKey = "${{ secrets.X_RAPID_API_KEY }}" > secrets.properties

      # Create Bundle AAB Release
      - name: Decode keystore
        run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore.jks

      - name: Build and Sign AAB
        run: |
          ./gradlew bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          JAVA_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=false -Dkotlin.incremental=false


      # Upload AAB Release
      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-aab
          path: app/build/outputs/bundle/release/app-release.aab

      # Build and Sign APK
      - name: Build and Sign APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          JAVA_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=false -Dkotlin.incremental=false

      # Upload APK Release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: app/build/outputs/apk/release/app-release.apk


      # Build and Sign APK DEBUG
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        env:
          JAVA_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=false -Dkotlin.incremental=false

      # Upload APK Release DEBUG
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

